Added bare metal form features
m15e/re-former pull request #3
Opened 2020-08-31 15:14 UTC by m15e

Created rails forms for new and update functionality following instructions from [Odin Project: Bare Metal Forms and Helpers](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)

2020-08-31 16:10 UTC, mikenath223 requested changes
### Hi Team. 👋

Nice work so far on this. 👌

However, let's fix this:

- [ ] Please also include the `form` and `form_tag` form methods in the `views/new` but comment both out. Also please use the `form_for` method, not `form_with`.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-08-31 16:11 UTC, mikenath223 commented on app/helpers/users_helper.rb
> +  end
- [ ] Please move this into the users' controller and make it a private method, because it deals with the params which shouldn't be public.

2020-08-31 16:12 UTC, mikenath223 commented on app/views/users/edit.html.erb
> +    <%= text_field(:user, :password) %>
- [ ] Also kindly make this a password_field, not a text field.

2020-09-01 12:06 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
#### Take note on one small suggestion below 👇 Thank you! 
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job :+1:
- You can now merge these changes.
- I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-09-01 12:06 UTC, christianotieno commented on app/views/users/_form.html.erb
> +    <%= submit_tag("Update") %>
```suggestion
    <%= submit_tag("Create") %>
```

2020-09-01 13:38 UTC, merged